[package]
name = "x86_vcpu"
version = "0.1.0"
edition = "2024"
authors = [
    "Mingxian Su <aarkegz@gmail.com>",
    "Keyang Hu <keyang.hu@qq.com>"
]
categories = ["virtualization", "no-std"]
description = "x86 Virtual CPU implementation for the Arceos Hypervisor"
repository = "https://github.com/arceos-hypervisor/x86_vcpu"
keywords = ["x86", "vcpu", "hypervisor", "arceos"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0" # MulanPubL2 is not included in SPDX

[dependencies]
log = "0.4.19"
cfg-if = "1.0"
bitflags = "2.2"
bit_field = "0.10"
paste = "1.0.15"
x86 = "0.52"
x86_64 = "0.15"
raw-cpuid = "11.0"
numeric-enum-macro = "0.2"

axerrno = "0.1.0"
page_table_entry = "0.5"
memory_addr = "0.4"
crate_interface = "0.1"

axaddrspace = "0.1.0"
axvcpu = "0.1.0"
x86_vlapic = "0.1.0"
axdevice_base = "0.1.0"
axvisor_api = "0.1.0"

spin = { version = "0.9", default-features = false }

[features]
default = ["vmx"]
tracing = []
vmx = []
svm = []
